swagger: '2.0'
info:
  version: 0.0.1
  title: RESTful API of Armadito Plugin for GLPI
  description: |
    Armadito Plugin for GLPI is accessible to agents by its RESTful API only.
    Thus, all communications between armadito agents and GLPI are described in this document.
    Note that there cannot be any connection initiated by server-side to directly access agents. Also, agents do not need to open any TCP ports of any kind.

    ## POST /api/agents

    Agents' enrollments are done by contacting this API. Server then send back to agents their dedicated identifier.

    ## GET /api/jobs

    To execute orders, agents simply check for available jobs periodically by sending a GET request to this endpoint.

    ## POST /api/jobs

    After job execution, an agent send job's results to plugin in a POST request.

    ## POST /api/scans

    Agents send antivirus scan results by connecting to this API endpoint.

    ## POST /api/states

    Agents send antiviruses states to this API endpoint. For example, it includes databases updates status for each antivirus.

    ## POST /api/alerts

    Virus alerts raised by managed antiviruses are send to this API endpoint.

host: armadito-glpi
paths:
  /glpi/plugins/armadito/api/jobs:
    get:
      description: |
        Gets an array of `PluginArmaditoJob` objects for the given **antivirus** installed on the device identified by the given **agent_id**.
      parameters:
        - name: agent_id
          in: query
          description: agent unique identifier
          required: true
          type: number
          format: double
      responses:
        '200':
          description: Successful response
          schema:
            title: ArrayOfPluginArmaditoJobs
            type: array
            items:
              $ref: "#/definitions/PluginArmaditoJob"
        default:
            description: Unexpected error
            schema:
              $ref: "#/definitions/PluginArmaditoError"
    post:
      description: |
        Update `PluginArmaditoJob` status with the given `PluginArmaditoJobStatus`.
      parameters:
          - in: body
            name: Enrollment
            description: JSON Enrollment object
            required: true
            schema:
              $ref: "#/definitions/PluginArmaditoJobStatus"
      responses:
        '200':
          description: Successful response

        400:
            description: Invalid Input
            schema:
              $ref: '#/definitions/PluginArmaditoError'
        500:
            description: Internal Server Error
            schema:
              $ref: '#/definitions/PluginArmaditoError'
  /glpi/plugins/armadito/api/agents:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      description:
        Add or Update `PluginArmaditoAgent` in database and return **agent_id**.
      parameters:
          - in: body
            name: Agent
            description: JSON Agent object
            required: true
            schema:
              $ref: "#/definitions/PluginArmaditoAgent"
      responses:
        '200':
          description: Successful response
          schema:
            title: agent_id
            type: number
            format: double
        400:
            description: Invalid Input
            schema:
              $ref: '#/definitions/PluginArmaditoError'
        500:
            description: Internal Server Error
            schema:
              $ref: '#/definitions/PluginArmaditoError'
  /glpi/plugins/armadito/api/states:
    post:
        consumes:
        - application/json
        produces:
        - application/json
        description:
         Given `PluginArmaditoState` object is stored in GLPI database and could be shown in user interface.
        parameters:
          - in: body
            name: State
            description: JSON State object
            required: true
            schema:
              $ref: "#/definitions/PluginArmaditoState"
        responses:
          '200':
            description: Successful response
          400:
            description: Invalid Input
            schema:
              $ref: '#/definitions/PluginArmaditoError'
          500:
            description: Internal Server Error
            schema:
              $ref: '#/definitions/PluginArmaditoError'
  /glpi/plugins/armadito/api/alerts:
    post:
        consumes:
          - application/json
        produces:
          - application/json
        description:
         Given `PluginArmaditoAlert` is stored in GLPI database and could be shown in user interface.
        parameters:
          - in: body
            name: Alert
            description: JSON Alert object
            required: true
            schema:
              $ref: "#/definitions/PluginArmaditoAlert"
        responses:
          '200':
            description: Successful response
          400:
            description: Invalid Input
            schema:
              $ref: '#/definitions/PluginArmaditoError'
          500:
            description: Internal Server Error
            schema:
              $ref: '#/definitions/PluginArmaditoError'
  /glpi/plugins/armadito/api/scans:
    post:
        consumes:
          - application/json
        produces:
          - application/json
        description:
         Given `PluginArmaditoScan` is stored in GLPI database and could be shown in user interface.
        parameters:
          - in: body
            name: Alert
            description: JSON Alert object
            required: true
            schema:
              $ref: "#/definitions/PluginArmaditoScan"
        responses:
          '200':
            description: Successful response
          400:
            description: Invalid Input
            schema:
              $ref: '#/definitions/PluginArmaditoError'
          500:
            description: Internal Server Error
            schema:
              $ref: '#/definitions/PluginArmaditoError'
definitions:
  PluginArmaditoError:
    type: object
    properties:
      error:
        type: string
  Antivirus:
    type: object
    properties:
      name:
        type: string
      version:
        type: string
  Task:
    type: object
    properties:
      name:
        type: string
      antivirus:
          $ref: '#/definitions/Antivirus'
      msg:
        type: string
  PluginArmaditoJob:
    type: object
    properties:
      type:
        type: string
      priority:
        type: string
      agent_id:
        type: number
        format: double
  PluginArmaditoJobStatus:
    type: object
    properties:
      job_id:
        type: string
      code:
        type: number
      message:
        type: string
  PluginArmaditoState:
    type: object
    properties:
      agent_id:
        type: number
        format: double
      agent_version:
        type: string
      task:
          $ref: '#/definitions/Task'
  PluginArmaditoAlert:
    type: object
    properties:
      agent_id:
        type: number
        format: double
      agent_version:
        type: string
      task:
        $ref: '#/definitions/Task'
  PluginArmaditoScan:
    type: object
    properties:
      agent_id:
        type: number
        format: double
      agent_version:
        type: string
      task:
        $ref: '#/definitions/Task'
  PluginArmaditoAgent:
    type: object
    properties:
      agent_id:
        type: number
        format: double
      agent_version:
        type: string
      uuid:
        type: string
      task:
        $ref: '#/definitions/Task'
